
buildscript {
    repositories {
        mavenLocal()
        mavenCentral()
        maven {url 'https://mauro-repository.com/libs-release-local'}
        maven {url 'https://mauro-repository.com/plugins-snapshot-local'}
        maven {url 'https://mauro-repository.com/plugins-release-local'}
        maven {url 'https://repo.gradle.org/gradle/libs-releases/'}
        maven {url 'https://plugins.gradle.org/m2/'}
    }
    dependencies {
        classpath "org.maurodata:mdm-gradle-plugin:$mdmGradlePluginVersion"
    }
}

plugins {
    id 'groovy'
}

apply plugin: 'uk.ac.ox.softeng.maurodatamapper.gradle.mdm-gradle'

apply from: 'dependencies.gradle'

repositories {
    mavenLocal()
    mavenCentral()
    maven {url "https://mauro-repository.com/libs-release-local"}
    maven {url "https://mauro-repository.com/libs-snapshot-local"}
    maven {url "https://repo.grails.org/grails/core"}
}

tasks.cpdCheck {
    ignoreFailures true
}
