# Core Info
version=5.4.0-SNAPSHOT
group=uk.ac.ox.softeng.maurodatamapper
# Gradle
gradleVersion=7.3.3
org.gradle.jvmargs=-Dfile.encoding=UTF-8 -Xmx2g
org.gradle.parallel=false
org.gradle.caching=true
# Code
sourceCompatibility=17
targetCompatibility=17
# Deployment & Build
mdmGradlePluginVersion=8.0.1
# Explode all plugins
exploded=true
# Grails
grailsVersion=5.3.2
grailsGradlePluginVersion=6.2.4
groovyVersion=3.0.11
grailsHibernate5Version=8.1.1
grailsViewsVersion=3.2.3
assetPipelineVersion=5.0.9
jaxbApiVersion=2.3.1
springBootVersion=4.1.1
# Previous mdm-core version for finding mdm-bom if current version not published yet
fallbackMdmCoreVersion=5.3.0-SNAPSHOT