#
# Copyright 2020 University of Oxford
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# SPDX-License-Identifier: Apache-2.0
#

maurodatamapper:
    security:
        public: false
    bootstrap:
        authority: true
    email:
        from:
            address: ''
---
simplejavamail:
    smtp:
        username: ''
        password: ''
        host: ''
        port: ''
    transportstrategy: SMTP_TLS
    javaxmail.debug: false
---
grails:
    gorm:
        failOnError: true
    controllers:
        upload:
            maxFileSize: 200000000
            maxRequestSize: 200000000
    cors:
        enabled: true
        allowCredentials: true
        # The following are the defaults
        # allowedOrigins: ['*'] # Cannot use allowedOrigins with *, they have to be clearly stated origins
        # allowedOriginPatterns: ['*']
        #exposedHeaders: null
        #maxAge: 1800
    databinding:
        dateFormats:
            - "yyyy-MM-dd'T'HH:mm:ss.SSSXXX"
            - "yyyy-MM-dd'T'HH:mm:ss.SSXXX"
            - "yyyy-MM-dd'T'HH:mm:ss.SXXX"
            - "yyyy-MM-dd'T'HH:mm:ssXXX"
            - 'yyyy-MM-dd HH:mm:ss.S'
            - "yyyy-MM-dd'T'HH:mm:ss'Z'"
            - "yyyy-MM-dd HH:mm:ss.S z"
            - "yyyy-MM-dd"
---
spring:
    flyway:
        enabled: true
        ignoreMissingMigrations: true
        baselineOnMigrate: true
---
hibernate:
    configClass: uk.ac.ox.softeng.maurodatamapper.core.hibernate.MauroDataMapperHibernateMappingContextConfiguration
    search:
        configuration_property_checking:
            strategy: ignore
        backend:
            lucene_version: 8.11.2
            analysis:
                configurer: 'class:uk.ac.ox.softeng.maurodatamapper.hibernate.search.backend.lucene.analysis.MdmLuceneAnalysisConfigurer'
        # Defaults
        massindexer:
            typesToIndexInParallel: 1
            cacheMode: IGNORE
            optimizeOnFinish: true
            optimizeAfterPurge: true
            purgeAllOnStart: true
            transactionTimeout: 1800
            threadsToLoadObjects: 20
            batchSizeToLoadObjects: 10000
            idFetchSize: -1 # Use postgres default
    cache:
        queries: false
        use_second_level_cache: true
        use_query_cache: true
        region:
            factory_class: org.hibernate.cache.jcache.JCacheRegionFactory
    javax:
        cache:
            provider: org.ehcache.jsr107.EhcacheCachingProvider
            missing_cache_strategy: create
    jdbc:
        batch_size: 100
        batch_versioned_data: true
    order_inserts: true
    order_updates: true
environments:
    test:
        grails:
            plugins:
                hibernatesearch:
                    rebuildIndexOnStart: false
    development:
        grails:
            plugins:
                hibernatesearch:
                    rebuildIndexOnStart: true
            views:
                markup:
                    cacheTemplates: false
    production:
        grails:
            plugins:
                hibernatesearch:
                    rebuildIndexOnStart: false